name: PHPStan CI

on:
  push:
  pull_request:

jobs:
  build:
    name: PHPStan analysis
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.0.28"
        pm-version-major: [ 4 ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: pmmp/setup-php-action@589cc43fddede20c8b0469828431d747fb1a1145
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
          pm-version-major: ${{ matrix.pm-version-major }}

      - name: Restore Composer package cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"

      - name: Install PHPStan Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze -c ./phpstan.neon.dist